### PR TITLE
Brooks dev

### PR DESCRIPTION
**Pull request by bcmcms**

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
Hi @bcmcms . Do you know why some of the plots appear empty? Is this just due to the y-axis range?

https://nbay11.fnal.gov/hb/cards/plots

**Comment by bcmcms** [comment]
> 
> 
> Hi @bcmcms . Do you know why some of the plots appear empty? Is this just due to the y-axis range?
> 
> https://nbay11.fnal.gov/hb/cards/plots

That's because I was only asked to plot slope vs qie number, so while the rest of the plots vs qie still get generated because of how things are booked, they don't get filled.

**Comment by caleb-james-smith** [comment]
Ah, ok. Is there a way to use a flag so that we don't create the empty plots?

**Comment by bcmcms** [comment]
I've written in a check for that. I can test it later tonight and commit it if everything works smoothly

**Comment by bcmcms** [comment]
It all seems to be in order.

**Comment by caleb-james-smith** [comment]
Awesome, thanks. That cleans up the site a bit and should lead to less confusion.

**Pull request merged**
